
title: Zen - An online platform where urban culture meets the underground.
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/zendigital.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# jekyll-paginate configuration

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
layouts_dir: ../_layouts
highlighter:         rouge
markdown: kramdown
permalink: pretty
source: .
destination: ../_site
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: assets/css
  style: :nested

port: 9090
